//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvs_Controller.NvsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NvsService.NvsContractService", CallbackContract=typeof(Nvs_Controller.NvsService.NvsContractServiceCallback))]
    public interface NvsContractService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/Subscribe", ReplyAction="http://tempuri.org/NvsContractService/SubscribeResponse")]
        void Subscribe(string p_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/UnSubscribe", ReplyAction="http://tempuri.org/NvsContractService/UnSubscribeResponse")]
        void UnSubscribe(string p_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/AllCode_CheckWCF", ReplyAction="http://tempuri.org/NvsContractService/AllCode_CheckWCFResponse")]
        string AllCode_CheckWCF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/User_Login", ReplyAction="http://tempuri.org/NvsContractService/User_LoginResponse")]
        ObjInfo.User_Info User_Login(string p_UserName, string p_PassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/Send_Msg", ReplyAction="http://tempuri.org/NvsContractService/Send_MsgResponse")]
        void Send_Msg(ObjInfo.Message_Info p_Message_Info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/Get_All_User", ReplyAction="http://tempuri.org/NvsContractService/Get_All_UserResponse")]
        ObjInfo.User_Info[] Get_All_User();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/Get_msgSend", ReplyAction="http://tempuri.org/NvsContractService/Get_msgSendResponse")]
        ObjInfo.Message_Info[] Get_msgSend(string p_UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/Get_msgReceive", ReplyAction="http://tempuri.org/NvsContractService/Get_msgReceiveResponse")]
        ObjInfo.Message_Info[] Get_msgReceive(string p_UserName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NvsContractServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/PushMessage", ReplyAction="http://tempuri.org/NvsContractService/PushMessageResponse")]
        void PushMessage(ObjInfo.Message_Info _data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/PushSession", ReplyAction="http://tempuri.org/NvsContractService/PushSessionResponse")]
        void PushSession(ObjInfo.Session_Info _data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NvsContractService/PushData", ReplyAction="http://tempuri.org/NvsContractService/PushDataResponse")]
        void PushData(string _data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NvsContractServiceChannel : Nvs_Controller.NvsService.NvsContractService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NvsContractServiceClient : System.ServiceModel.DuplexClientBase<Nvs_Controller.NvsService.NvsContractService>, Nvs_Controller.NvsService.NvsContractService {
        
        public NvsContractServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public NvsContractServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public NvsContractServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NvsContractServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NvsContractServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(string p_id) {
            base.Channel.Subscribe(p_id);
        }
        
        public void UnSubscribe(string p_id) {
            base.Channel.UnSubscribe(p_id);
        }
        
        public string AllCode_CheckWCF() {
            return base.Channel.AllCode_CheckWCF();
        }
        
        public ObjInfo.User_Info User_Login(string p_UserName, string p_PassWord) {
            return base.Channel.User_Login(p_UserName, p_PassWord);
        }
        
        public void Send_Msg(ObjInfo.Message_Info p_Message_Info) {
            base.Channel.Send_Msg(p_Message_Info);
        }
        
        public ObjInfo.User_Info[] Get_All_User() {
            return base.Channel.Get_All_User();
        }
        
        public ObjInfo.Message_Info[] Get_msgSend(string p_UserName) {
            return base.Channel.Get_msgSend(p_UserName);
        }
        
        public ObjInfo.Message_Info[] Get_msgReceive(string p_UserName) {
            return base.Channel.Get_msgReceive(p_UserName);
        }
    }
}
